In [1]:
import pandas as pd
method_duration_data = pd.read_pickle('method_duration_data.pkl')
method_duration_data['date']

0      2021-06-12
1      2021-06-12
2      2021-06-12
3      2021-06-12
4      2021-06-12
          ...
5968   1999-01-08
5969   1999-01-08
5970   1998-10-16
5971   1998-10-16
5972   1998-10-16
Name: date, Length: 5973, dtype: datetime64[ns]

In [2]:
fights_strings_removed = pd.read_pickle('fights_strings_removed.pkl')
fights_strings_removed['date']

0      2021-06-12
1      2021-06-12
2      2020-07-18
3      2019-09-21
4      2020-07-25
          ...
5865   1999-09-24
5866   1999-07-16
5867   1999-07-16
5868   1999-05-07
5869   1999-03-05
Name: date, Length: 5870, dtype: datetime64[ns]

In [3]:
method_duration_data['duration']

0       900.0
1         7.0
2       900.0
3       900.0
4       119.0
        ...
5968    480.0
5969    451.0
5970    780.0
5971    487.0
5972     44.0
Name: duration, Length: 5973, dtype: float64

In [81]:
method = []
duration = []
for index, row in fights_strings_removed.iterrows():
    data = method_duration_data.loc[((method_duration_data['fighter_1'] == row['fighter 1'])
                                     & (method_duration_data['fighter_2'] == row['fighter 2']))  
                                    | ((method_duration_data['fighter_1'] == row['fighter 2'])
                                       & (method_duration_data['fighter_2'] == row['fighter 1']))]
    
    method.append(data['method'].values)
    duration.append(data['duration'].values)
    
print(len(method))
print(len(duration))

5870
5870

In [82]:
count = 0
for arr in method:
    if len(arr) == 0:
        count+=1
print(count)

count = 0
print(count)
for arr in duration:
    if len(arr) == 0:
        count+=1
print(count)
    
fights_strings_removed['method'] = method
fights_strings_removed['duration'] = duration
fights_strings_removed

2908
0
2908

,result 1,fighter 1,Sig. str 1,Sig. str. % 1,Head 1,Body 1,Leg 1,Distance 1,Clinch 1,Ground 1,...,Stance 2_Open Stance,Stance 2_Orthodox,Stance 2_Sideways,Stance 2_Southpaw,Stance 2_Switch,Stance 1_Sideways,tdd1,tdd2,method,duration
0,0,Dusko Todorovic,37,30,23,10,4,27,10,0,...,0,1,0,0,0,0.0,2,4,[Decision - Unanimous],[900.0]
1,0,Francisco Trinaldo,39,30,22,16,1,34,5,0,...,0,1,0,0,0,0.0,1,1,[KO/TKO],[64.0]
2,0,Elizeu Zaleski dos Santos,46,33,23,11,12,35,3,8,...,0,1,0,0,0,0.0,3,4,[Decision - Unanimous],[900.0]
3,0,Nordine Taleb,6,23,3,0,3,6,0,0,...,0,1,0,0,0,0.0,0,0,[Decision - Unanimous],[900.0]
4,1,Francisco Trinaldo,30,51,15,7,8,19,3,8,...,0,1,0,0,0,0.0,0,1,[Decision - Unanimous],[900.0]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5865,1,Marcelo Mello,7,53,6,1,0,1,0,6,...,0,1,0,0,0,0.0,0,1,[],[]
5866,1,Gary Goodridge,8,57,6,0,2,6,2,0,...,0,1,0,0,0,0.0,0,0,[],[]
5867,1,Sione Latu,9,47,6,2,1,3,4,2,...,0,1,0,0,0,0.0,1,0,[],[]
5868,1,Mikey Burnett,42,31,28,9,5,21,19,2,...,0,1,0,0,0,0.0,6,0,[],[]
5869,1,Tulio Palhares,31,70,26,1,4,11,1,19,...,0,1,0,0,0,0.0,1,0,[],[]

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)