In [35]:
import pandas as pd

fighter_data = pd.read_pickle("fighter_data.pkl")
fights_data = pd.read_pickle("fights_data_cleaning2.pkl")

# merge on fighter 1
combined_fighter_fights_data1 = pd.merge(fights_data, fighter_data, left_on='fighter 1', right_on='Name')

# clean and rename columns
del combined_fighter_fights_data1['Name']
combined_fighter_fights_data1.rename(columns={'Height': 'Height 1', 'Weight': 'Weight 1', 'Stance': 'Stance 1', 'Record': 'Record 1'}, inplace=True)

# merge on fighter 2
combined_fighter_fights_data_final = pd.merge(combined_fighter_fights_data1, fighter_data, left_on='fighter 2', right_on='Name')

# clean and rename columns
del combined_fighter_fights_data_final['Name']
combined_fighter_fights_data_final.rename(columns={'Height': 'Height 2', 'Weight': 'Weight 2', 'Stance': 'Stance 2', 'Record': 'Record 2'}, inplace=True)


list(combined_fighter_fights_data_final.columns)
combined_fighter_fights_data_final

,result 1,fighter 1,Sig. str 1,Sig. str. % 1,Head 1,Body 1,Leg 1,Distance 1,Clinch 1,Ground 1,...,Sig. str defended2,Td attempted 2,Height 1,Weight 1,Stance 1,Record 1,Height 2,Weight 2,Stance 2,Record 2
0,L,Dusko Todorovic,37,30%,23,10,4,27,10,0,...,83,5,73.000000,185.0,Orthodox,"[10, 2, 0]",75.000000,185.000000,Orthodox,"[8, 3, 0]"
1,L,Francisco Trinaldo,39,30%,22,16,1,34,5,0,...,89,3,69.000000,155.0,Southpaw,"[26, 8, 0]",71.000000,170.000000,Orthodox,"[18, 2, 0]"
2,L,Elizeu Zaleski dos Santos,46,33%,23,11,12,35,3,8,...,92,3,71.000000,170.0,Orthodox,"[22, 7, 0]",71.000000,170.000000,Orthodox,"[18, 2, 0]"
3,L,Nordine Taleb,6,23%,3,0,3,6,0,0,...,20,0,73.000000,170.0,Orthodox,"[15, 7, 0]",71.000000,170.000000,Orthodox,"[18, 2, 0]"
4,W,Francisco Trinaldo,30,51%,15,7,8,19,3,8,...,28,0,69.000000,155.0,Southpaw,"[26, 8, 0]",73.000000,155.000000,Orthodox,"[10, 2, 0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5865,W,Marcelo Mello,7,53%,6,1,0,1,0,6,...,6,0,67.000000,170.0,Southpaw,"[1, 0, 0]",73.000000,170.000000,Orthodox,"[5, 8, 0]"
5866,W,Gary Goodridge,8,57%,6,0,2,6,2,0,...,6,0,75.000000,249.0,Orthodox,"[23, 22, 1]",74.000000,345.000000,Orthodox,"[14, 2, 1]"
5867,W,Sione Latu,9,47%,6,2,1,3,4,2,...,10,2,72.000000,215.0,Orthodox,"[1, 0, 0]",74.000000,200.000000,Orthodox,"[4, 3, 0]"
5868,W,Mikey Burnett,42,31%,28,9,5,21,19,2,...,93,6,66.000000,170.0,Orthodox,"[5, 2, 0]",65.000000,170.000000,Orthodox,"[0, 2, 0]"
5869,W,Tulio Palhares,31,70%,26,1,4,11,1,19,...,13,3,70.293459,180.0,Orthodox,"[2, 16, 0]",70.293459,172.836029,Orthodox,"[0, 1, 0]"

In [30]:
combined_fighter_fights_data_final.to_pickle("fights_data_cleaning2.pkl")

,result 1,fighter 1,Sig. str 1,Sig. str. % 1,Head 1,Body 1,Leg 1,Distance 1,Clinch 1,Ground 1,...,Sig. str defended1,Td attempted 1,Sig. str attempted2,Sig. str absorbed2,Sig. str defended2,Td attempted 2,Height 1,Weight 1,Stance 1,Record 1
0,L,Dusko Todorovic,37,30%,23,10,4,27,10,0,...,79,4,150,37,83,5,73.000000,185.0,Orthodox,"[10, 2, 0]"
1,L,Francisco Trinaldo,39,30%,22,16,1,34,5,0,...,56,1,118,39,89,3,69.000000,155.0,Southpaw,"[26, 8, 0]"
2,W,Francisco Trinaldo,30,51%,15,7,8,19,3,8,...,49,3,70,30,28,0,69.000000,155.0,Southpaw,"[26, 8, 0]"
3,W,Francisco Trinaldo,55,43%,34,17,4,53,2,0,...,56,1,123,55,71,0,69.000000,155.0,Southpaw,"[26, 8, 0]"
4,W,Francisco Trinaldo,31,25%,20,5,6,26,5,0,...,65,2,115,31,91,2,69.000000,155.0,Southpaw,"[26, 8, 0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5858,W,Gary Goodridge,8,57%,6,0,2,6,2,0,...,1,0,3,8,6,0,75.000000,249.0,Orthodox,"[23, 22, 1]"
5859,W,Sione Latu,9,47%,6,2,1,3,4,2,...,25,1,42,9,10,2,72.000000,215.0,Orthodox,"[1, 0, 0]"
5860,W,Mikey Burnett,42,31%,28,9,5,21,19,2,...,29,0,63,42,93,6,66.000000,170.0,Orthodox,"[5, 2, 0]"
5861,W,Tulio Palhares,31,70%,26,1,4,11,1,19,...,25,4,36,31,13,3,70.293459,180.0,Orthodox,"[2, 16, 0]"
5862,W,Ebenezer Fontes Braga,9,56%,6,1,2,2,5,2,...,2,1,5,9,7,0,72.000000,199.0,Orthodox,"[13, 7, 2]"