In [6]:
import pandas as pd
fighter_data = pd.read_pickle("fighter_data.pkl")
fights_data = pd.read_pickle("fights_data.pkl")

fights_data_cleaned = pd.concat([fights_data.drop(['stats'], axis=1), fights_data['stats'].apply(pd.Series)], axis=1).drop(['Fighter'], axis=1)
fights_data_cleaned


fights_data_cleaned

,result,fighter,date,Sig. str,Sig. str. %,Head,Body,Leg,Distance,Clinch,Ground,KD,Sig. str.,Total str.,Td,Td %,Sub. att,Rev.,Ctrl
0,L,Dusko Todorovic,2021-06-12,37 of 120,30%,23 of 103,10 of 13,4 of 4,27 of 106,10 of 14,0 of 0,0,37 of 120,46 of 133,0 of 4,0%,0,0,1:26
1,L,Gregory Rodrigues,2021-06-12,71 of 150,47%,49 of 120,19 of 24,3 of 6,63 of 136,8 of 14,0 of 0,0,71 of 150,73 of 153,3 of 5,60%,0,0,1:25
2,L,Francisco Trinaldo,2021-06-12,39 of 128,30%,22 of 101,16 of 26,1 of 1,34 of 119,5 of 9,0 of 0,0,39 of 128,51 of 148,0 of 1,0%,0,0,0:40
3,L,Muslim Salikhov,2021-06-12,62 of 118,52%,29 of 84,26 of 27,7 of 7,48 of 98,1 of 1,13 of 19,1,62 of 118,71 of 129,2 of 3,66%,0,0,2:07
4,L,Makwan Amirkhani,2021-06-12,20 of 49,40%,14 of 40,4 of 7,2 of 2,15 of 42,0 of 0,5 of 7,0,20 of 49,25 of 56,5 of 9,55%,0,0,6:50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11917,L,Adriano Santos,1999-03-05,11 of 36,30%,8 of 30,2 of 3,1 of 3,4 of 24,0 of 0,7 of 12,0,11 of 36,21 of 47,2 of 3,66%,0,1,--
11918,W,Ebenezer Fontes Braga,1999-03-05,9 of 16,56%,6 of 11,1 of 3,2 of 2,2 of 2,5 of 10,2 of 4,0,9 of 16,17 of 26,1 of 1,100%,1,0,--
11919,L,Jeremy Horn,1999-03-05,3 of 5,60%,0 of 1,3 of 4,0 of 0,0 of 0,3 of 5,0 of 0,0,3 of 5,11 of 13,0 of 0,---,0,0,--
11920,W,Frank Shamrock,1999-03-05,23 of 33,69%,5 of 12,8 of 10,10 of 11,8 of 12,7 of 10,8 of 11,2,23 of 33,55 of 67,0 of 0,---,4,2,--
11921,L,John Lober,1999-03-05,4 of 11,36%,3 of 10,0 of 0,1 of 1,1 of 8,0 of 0,3 of 3,0,4 of 11,11 of 18,3 of 4,75%,1,0,--

In [12]:
result1 = []
fighter1 = []
sigstr1 = []
sigstrperc1 = []
head1 = []
body1 = []
leg1 = []
distance1 = []
clinch1 = []
ground1 = []
kd1 = []
totalstr1 = []
td1 = []
tdperc1 = []
subatt1 = []
rev1 = []
ctrl1 = []



result2 = []
fighter2 = []
sigstr2 = []
sigstrperc2 = []
head2 = []
body2 = []
leg2 = []
distance2 = []
clinch2 = []
ground2 = []
kd2 = []
totalstr2 = []
td2 = []
tdperc2 = []
subatt2 = []
rev2 = []
ctrl2 = []



for index, row in fights_data_cleaned.iterrows():
    if (index % 2) == 0:
        result1.append(row['result'])
        fighter1.append(row['fighter'])
        sigstr1.append(row['Sig. str'])
        sigstrperc1.append(row['Sig. str. %'])
        head1.append(row['Head'])
        body1.append(row['Body'])
        leg1.append(row['Leg'])
        distance1.append(row['Distance'])
        clinch1.append(row['Clinch'])
        ground1.append(row['Ground'])
        kd1.append(row['KD'])
        totalstr1.append(row['Total str.'])
        td1.append(row['Td'])
        tdperc1.append(row['Td %'])
        subatt1.append(row['Sub. att'])
        rev1.append(row['Rev.'])
        ctrl1.append(row['Ctrl'])
    else:
        result2.append(row['result'])
        fighter2.append(row['fighter'])
        sigstr2.append(row['Sig. str'])
        sigstrperc2.append(row['Sig. str. %'])
        head2.append(row['Head'])
        body2.append(row['Body'])
        leg2.append(row['Leg'])
        distance2.append(row['Distance'])
        clinch2.append(row['Clinch'])
        ground2.append(row['Ground'])
        kd2.append(row['KD'])
        totalstr2.append(row['Total str.'])
        td2.append(row['Td'])
        tdperc2.append(row['Td %'])
        subatt2.append(row['Sub. att'])
        rev2.append(row['Rev.'])
        ctrl2.append(row['Ctrl'])

In [15]:
from pandas import DataFrame
rows = [result1, fighter1, sigstr1, sigstrperc1, head1, body1, leg1, distance1, 
        clinch1, ground1, kd1, totalstr1, td1, tdperc1, subatt1, rev1, ctrl1, 
        result2, fighter2, sigstr2, sigstrperc2, head2, body2, leg2, distance2,
        clinch2, ground2, kd2, totalstr2, td2, tdperc2, subatt2, rev2, ctrl2]
df = DataFrame (rows).transpose()
df.columns = ['result 1', 'fighter 1', 'Sig. str 1', 'Sig. str. % 1',
              'Head 1', 'Body 1', 'Leg 1', 'Distance 1', 'Clinch 1', 'Ground 1', 
             'KD 1', 'Total str. 1', 'Td 1', 'Td % 1', 'Sub. att 1', 'Rev. 1', 'Ctrl 1', 
             'result 2', 'fighter 2', 'Sig. str 2', 'Sig. str. % 2',
              'Head 2', 'Body 2', 'Leg 2', 'Distance 2', 'Clinch 2', 'Ground 2', 
             'KD 2', 'Total str. 2', 'Td 2', 'Td % 2', 'Sub. att 2', 'Rev. 2', 'Ctrl 2']
df
df.to_pickle('fights-data-cleaned.pkl')