In [52]:
import pandas as pd

fighter_data = pd.read_pickle("fighter_data.pkl")
fights_data = pd.read_pickle("fights_data_cleaning2.pkl")

# # merge on fighter 1
# combined_fighter_fights_data1 = pd.merge(fights_data, fighter_data, left_on='fighter 1', right_on='Name')

# # clean and rename columns
# del combined_fighter_fights_data1['Name']
# combined_fighter_fights_data1.rename(columns={'Height': 'Height 1', 'Weight': 'Weight 1', 'Stance': 'Stance 1', 'Record': 'Record 1'}, inplace=True)

# # merge on fighter 2
# combined_fighter_fights_data_final = pd.merge(combined_fighter_fights_data1, fighter_data, left_on='fighter 2', right_on='Name')

# # clean and rename columns
# del combined_fighter_fights_data_final['Name']
# combined_fighter_fights_data_final.rename(columns={'Height': 'Height 2', 'Weight': 'Weight 2', 'Stance': 'Stance 2', 'Record': 'Record 2'}, inplace=True)


# list(combined_fighter_fights_data_final.columns)
# combined_fighter_fights_data_final

In [53]:
#combined_fighter_fights_data_final.to_pickle("fights_data_cleaning2.pkl")

In [59]:
#fighter 1
heights1 = []
weights1 = []
stance1 = []


for f in fights_data["fighter 1"]:
    try:
        h = float(fighter_data[fighter_data["Name"] == f]["Height"])
        w = float(fighter_data[fighter_data["Name"] == f]["Weight"])
        s = str(fighter_data[fighter_data["Name"] == f]["Stance"]).split(" ")[4].split()[0]
    except:
        h = 0
        w = 0
        s = 0
    heights1.append(h)
    weights1.append(w)
    stance1.append(s)

In [60]:
len(heights1)

5865

In [57]:
fighter_data[fighter_data["Name"] == "Drew Dober"]["Height"]

807    68.0
Name: Height, dtype: float64

In [51]:
heights1[0]

68.0

In [61]:
#fighter 2
heights2 = []
weights2 = []
stance2 = []

for f in fights_data["fighter 2"]:
    try:
        h = float(fighter_data[fighter_data["Name"] == f]["Height"])
        w = float(fighter_data[fighter_data["Name"] == f]["Weight"])
        s = str(fighter_data[fighter_data["Name"] == f]["Stance"]).split(" ")[4].split()[0]
    except:
        h = 0
        w = 0
        s = 0
    heights2.append(h)
    weights2.append(w)
    stance2.append(s)

In [62]:
fights_data["Height 1"] = heights1
fights_data["Weight 1"] = weights1
fights_data["Stance 1"] = stance1

fights_data["Height 2"] = heights2
fights_data["Weight 2"] = weights2
fights_data["Stance 2"] = stance2

In [48]:
str(stance2[0]).split(" ")[4].split()[0]

'Orthodox'

In [24]:
w

145.0

In [63]:
fights_data

,result 1,fighter 1,Sig. str 1,Sig. str. % 1,Head 1,Body 1,Leg 1,Distance 1,Clinch 1,Ground 1,...,Sig. str attempted2,Sig. str absorbed2,Sig. str defended2,Td attempted 2,Height 1,Weight 1,Stance 1,Height 2,Weight 2,Stance 2
0,L,Drew Dober,73,43%,52,18,3,67,2,4,...,137,73,95,11,68.0,155.0,Southpaw,67.0,155.0,Orthodox
1,L,Chase Hooper,31,50%,21,9,1,28,0,3,...,68,31,30,1,73.0,145.0,Southpaw,70.0,145.0,Orthodox
2,W,Eryk Anders,44,59%,36,7,1,9,17,18,...,58,44,30,4,73.0,185.0,Southpaw,72.0,185.0,Orthodox
3,W,Paul Craig,23,92%,18,4,1,6,0,17,...,8,23,2,0,75.0,205.0,Orthodox,76.0,205.0,Southpaw
4,W,Israel Adesanya,96,53%,44,11,41,85,10,1,...,176,96,85,14,76.0,185.0,Switch,72.0,185.0,Southpaw
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5969,W,Mikey Burnett,42,31%,28,9,5,21,19,2,...,63,42,93,6,66.0,170.0,Orthodox,65.0,170.0,Orthodox
5970,W,Vitor Belfort,7,53%,7,0,0,7,0,0,...,2,7,6,0,72.0,185.0,Southpaw,71.0,205.0,Orthodox
5971,W,Pat Miletich,19,55%,2,12,5,4,15,0,...,43,19,15,2,70.0,170.0,Orthodox,66.0,170.0,Orthodox
5972,W,Ebenezer Fontes Braga,9,56%,6,1,2,2,5,2,...,5,9,7,0,72.0,199.0,Orthodox,73.0,185.0,Orthodox
5973,W,Tsuyoshi Kohsaka,14,35%,7,4,3,11,0,3,...,67,14,26,0,71.0,225.0,Orthodox,75.0,235.0,Orthodox

In [70]:
#some missing data
#replace any zeros, for height we will take the mean
heights1 = []
for h in fights_data["Height 1"]:
    if h == 0:
        heights1.append(fights_data["Height 1"].mean())
    else:
        heights1.append(h)

heights2 = []
for h in fights_data["Height 2"]:
    if h == 0:
        heights2.append(fights_data["Height 2"].mean())
    else:
        heights2.append(h)

fights_data["Height 1"] = heights1
fights_data["Height 2"] = heights2

In [73]:
#for stance most people are orthodox so we will put that in for missing stances

In [72]:
stance1 = []
stance2 = []

for s in fights_data["Stance 1"]:
    if s == 0:
        stance1.append("Orthodox")
    else:
        stance1.append(s)

for s in fights_data["Stance 2"]:
    if s == 0:
        stance2.append("Orthodox")
    else:
        stance2.append(s)

fights_data["Stance 1"] = stance1
fights_data["Stance 2"] = stance2

In [88]:
#now weight is a lil trickier, fights are in a weight class, 
#so if weight 1 is missing, we will put the corresponding weight 2 value
weight1 = []
weight2 = []

In [89]:
for i in fights_data.index:
    try:
        if fights_data["Weight 1"][i] == 0:
            weight1.append(fights_data["Weight 2"][i])
        else:
            weight1.append(fights_data["Weight 1"][i])
    except:
        pass
        
for i in fights_data.index:
    try:
        if fights_data["Weight 2"][i] == 0:
            weight2.append(fights_data["Weight 1"][i])
        else:
            weight2.append(fights_data["Weight 2"][i])
    except:
        pass
        
fights_data["Weight 1"] = weight1
fights_data["Weight 2"] = weight2

In [95]:
fighter_data

                     Name     Height  Weight    Stance       Record
0               Tom Aaron  70.293459   155.0  Orthodox    [5, 3, 0]
1            Danny Abbadi  71.000000   155.0  Orthodox    [4, 6, 0]
2            David Abbott  72.000000   265.0    Switch  [10, 15, 0]
3     Shamil Abdurakhimov  75.000000   235.0  Orthodox   [20, 5, 0]
4            Hiroyuki Abe  66.000000   145.0  Orthodox   [8, 15, 3]
...                   ...        ...     ...       ...          ...
3657        Dave Zitanick  70.293459   170.0  Orthodox    [5, 7, 0]
3658          Alex Zuniga  70.293459   145.0  Orthodox    [6, 3, 0]
3659        George Zuniga  69.000000   185.0  Orthodox    [3, 1, 0]
3660         Allan Zuniga  67.000000   155.0  Orthodox   [13, 1, 0]
3661       Virgil Zwicker  74.000000   205.0  Orthodox   [15, 6, 1]

[3662 rows x 5 columns]

In [105]:
#records
#fighter 1
records1 = []


for f in fights_data["fighter 1"]:
    try:
        r = list(fighter_data[fighter_data["Name"] == f]["Record"])[0]
    except:
        r = 0
    records1.append(r)

In [106]:
records2 = []


for f in fights_data["fighter 2"]:
    try:
        r = list(fighter_data[fighter_data["Name"] == f]["Record"])[0]
    except:
        r = 0
    records2.append(r)

In [107]:
fights_data["Record 1"] = records1
fights_data["Record 2"] = records2

In [112]:
fights_data.to_pickle("fighter_fights_combined.pkl")